project_id = "yzyacfmiacyqqldohgnr"

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.ai-chat]
verify_jwt = false